# Site settings
title: ReiMUN
email:
description: The website of Reigate Grammar School's Model United Nations conference, ReiMUN.
baseurl: ""
url: "reimun.github.io"

# Build settings
markdown: kramdown

# Allow GFM to render
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
