name : Foundation5/github pages/Jykill starter
brand : Warwick UN Society
description : The website for Warwick UN Society
keyword :
url :
email :
twitter : WarwickMUN
instagram: WarwickMUN
github : AGilchrist0
author : Aaron Gilchrist
year : 2019
markdown : kramdown
exclude :
  - node_modules
sass:
    sass_dir: /css
    style: compressed
